### ISSUE TITLE
[ErrorException] symlink(): Protocol error

### ISSUE THREAD

**Issue by MatheusRV** [MatheusRV/Cachet-Sandstorm#1]
```
#vagrant-spk dev
Calling 'vagrant' 'ssh' '-c' '/opt/app/.sandstorm/build.sh && cd /opt/app/.sandstorm && spk dev --pkg-def=/opt/app/.sandstorm/sandstorm-pkgdef.capnp:pkgdef' in /mnt/c/Users/mathe/Dev/Cachet-Sandstorm/.sandstorm
vagrant@127.0.0.1's password:

[...]

  [ErrorException]
  symlink(): Protocol error


Connection to 127.0.0.1 closed.
Command failed with a non-zero exit status (1).
```

Laravel log:
```
[2017-06-14 01:11:06] production.ERROR: exception 'ErrorException' with message 'symlink(): Protocol error' in /opt/app/bootstrap/cache/compiled.php:7558
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'symlink(): Prot...', '/opt/app/bootst...', 7558, Array)
#1 /opt/app/bootstrap/cache/compiled.php(7558): symlink('/opt/app/storag...', '/opt/app/public...')
#2 /opt/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/StorageLinkCommand.php(34): Illuminate\Filesystem\Filesystem->link('/opt/app/storag...', '/opt/app/public...')
#3 [internal function]: Illuminate\Foundation\Console\StorageLinkCommand->fire()
#4 /opt/app/bootstrap/cache/compiled.php(1375): call_user_func_array(Array, Array)
#5 /opt/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#6 /opt/app/vendor/symfony/console/Command/Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#7 /opt/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#8 /opt/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(185): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#9 /opt/app/vendor/graham-campbell/core/src/Subscribers/CommandSubscriber.php(138): Illuminate\Console\Command->call('storage:link')
#10 [internal function]: GrahamCampbell\Core\Subscribers\CommandSubscriber->onLinkStorage(Object(GrahamCampbell\Core\Console\Commands\AppInstall))
#11 /opt/app/bootstrap/cache/compiled.php(10332): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(GrahamCampbell\Core\Console\Commands\AppInstall))
#13 /opt/app/bootstrap/cache/compiled.php(10266): call_user_func_array(Object(Closure), Array)
#14 /opt/app/vendor/graham-campbell/core/src/Console/Commands/AppInstall.php(74): Illuminate\Events\Dispatcher->fire('command.linksto...', Object(GrahamCampbell\Core\Console\Commands\AppInstall))
#15 [internal function]: GrahamCampbell\Core\Console\Commands\AppInstall->handle()
#16 /opt/app/bootstrap/cache/compiled.php(1375): call_user_func_array(Array, Array)
#17 /opt/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#18 /opt/app/vendor/symfony/console/Command/Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /opt/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /opt/app/vendor/symfony/console/Application.php(817): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /opt/app/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(GrahamCampbell\Core\Console\Commands\AppInstall), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /opt/app/vendor/symfony/console/Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /opt/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /opt/app/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main} {"identification":{"id":"33d75522-d6fd-4dea-9f34-0cba92d060ad"}} 
```

**Comment by MatheusRV** [comment]
this is just a WSL bug, you need to open Bash with 'Run as Administrator'.
